//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga4ISP97YulinGolovin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int IdProduct { get; set; }
        public string Title { get; set; }
        public int IdCategory { get; set; }
        public decimal Cost { get; set; }
        public string ShortDescription { get; set; }
        public string ProductComposition { get; set; }
        public string PhotoPath { get; set; }
        public int CaloriesQty { get; set; }
        public int ProductWeightInGR { get; set; }
        public bool InStock { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
